-- Nombre alumnos/as:
-- Tema específico del proyecto:
-- Nº de etapa:

/*
DISEÑO FÍSICO (RA2)
A continuación, implementa en lenguaje SQL todas las sentencias necesarias para generar la BD. Las sentencias SQL, además de las tablas, deben incluir la creación de la BD.
*/

CREATE DATABASE ...
CREATE TABLE...


/*
LENGUAJE DE MANIPULACIÓN DE DATOS (RA3 y RA4)
Este fichero debe tener todas las órdenes necesarias para realizar las operaciones de manipulación exigidas por la etapa de proyecto.*/

/*INSERCIONES: Realiza todas las inserciones necesarias para que el resultado de las consultas arroje varios resultados, pero no todos los registros de una tabla.*/

INSERT INTO...

/*CONSULTAS: Nota: Se incluirá como comentario el enunciado de cada consulta.*/

--Diseña una consulta para...
SELECT...

/*PROCEDIMIENTOS ALMACENADOS (RA5)
Órdenes necesarias para implementar y ejecutar los procedimientos almacenados descritos en los enunciados.
Notas: 
- Se incluirá como comentario el enunciado cada script.
- Todos los procedimientos, funciones, triggers, etc. deberán contar con sentencias (CALL, etc.) que permitan comprobar su funcionamiento.*/

-- Crea un procedimiento y pruébalo...
CREATE PROCEDURE...
CALL ...
-- Crea una función y pruébala...
CREATE FUNCTION ...
SELECT ...
-- Crea un trigger y pruébalo...
CREATE TRIGGER ...
INSERT...

-- ETC.
